### PR TITLE
Add bike locations in 3 languages

### LINKED ISSUE #2: Add address and location description in 3 languages
## Separate scraping

This should be a separate scraping process as the data would only change daily at most.

Also, different languages need to be scraped, which 3-doubles the amount of HTTP requests

## Modeling

Use the properties:
 * http://schema.org/address
 * http://schema.org/location

In order to use different languages, follow the JSON-LD specification:
```json
"location": [
 {
 "@language": "nl",
 "@value": "Meteen voor het station"
 },
 {
  "@language": "en",
   "@value": "Immediately outside the station"
 }
]
```

### PR DESCRIPTION
**Pull request by archived-m**
Closes #2 

This adds the `address` and `location` field to the geojson features (if they are supplied on the website), and are always filled in Dutch, even on a standard run.

When supplying the `--full` flag to the command, it also adds locations in French and English.

### CODE REVIEW

**Comment by pietercolpaert** [comment]
@MichielLeyman Can you resolve conflicts?

**Review by pietercolpaert — APPROVED** [review]

**Review by pietercolpaert — CHANGES_REQUESTED** [review]
* [x] I want a `--lang` flag instead that *only* extracts the addresses and locations
 * [x] When an empty string is found, the property should not be added
 * [x] I should fix the partial strings problem (although I’m not entirely sure anymore where the problem lies)

**Comment by archived-m** [comment]
I couldn't omit the `longitude` and `latitude` properties on a `--lang` run, because I use them together as an identifier to set the english and french location props.

Other than the partial strings, it should be ready to merge. Would tackle that in a separate PR

**Comment by archived-m** [comment]
Partial strings problem fixed by replacing all nasty single quotes before parsing (goeien bal Julian)

Closes #5

**Pull request merged**
